apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "1 13 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      activeDeadlineSeconds: 7200
      template:
        metadata:
          labels:
            app: cron
        spec:
          containers:
            - name: test
              image: test
              resources:
                requests:
                  memory: 896Mi
              args:
                - --test
              envFrom:
                - configMapRef:
                    name: server-cron
              volumeMounts:
                - name: service-account-creds
                  mountPath: /secret
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: service-account-creds
              secret:
                secretName: service-account-creds

