on:
  pull_request:
    paths:
    - 'kubernetes/**'

name: Test Kuberenetes Manifests with our policies
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed objects
      uses: b4b4r07/action-changed-objects@master
      with:
        added: 'true'
        deleted: 'false'
        modified: 'true'
      id: objects
    - name: Run conftest
      uses: YubicoLabs/action-conftest@v2
      with:
        files: ${{ steps.objects.outputs.changed }}
        policy: ./policy
        all-namespaces: true
