on:
  pull_request:
    paths:
    - 'policy/**'

name: Run unit test against our rego policies
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed objects
      uses: b4b4r07/action-changed-objects@master
      with:
        added: 'true'
        deleted: 'false'
        modified: 'true'
      id: objects
    - name: Run opa test against changed files
      uses: b4b4r07/action-opa@master
      if: steps.objects.outputs.changed
      with:
        coverage: 90%
        files: ${{ steps.objects.outputs.changed }}
      id: opa
    - name: Post opa command result to GitHub comment
      uses: b4b4r07/action-github-comment@master
      if: steps.opa.outputs.result
      with:
        body: |
          ## opa test result
          ```
          ${{ steps.opa.outputs.result }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
