on:
  pull_request:
    paths:
    - 'kubernetes/**'

name: Test Kuberenetes Manifests with our policies
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed objects
      uses: b4b4r07/action-changed-objects@master
      with:
        added: 'true'
        deleted: 'false'
        modified: 'true'
      id: objects
    - name: Run conftest test against changed files
      uses: b4b4r07/action-conftest@master
      if: steps.objects.outputs.changed
      with:
        files: ${{ steps.objects.outputs.changed }}
        # policy: 'policy'
        all-namespaces: true
        log-level: trace
      id: conftest
    - name: Post conftest command result to GitHub comment
      uses: b4b4r07/action-github-comment@master
      if: always() && steps.conftest.outputs.result
      with:
        body: |
          ## conftest test result
          ```
          ${{ steps.conftest.outputs.result }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG: trace
